# In consumer repo
name: Trigger DevAssist Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: erinehart1/devAssist-Shared-Actions/.github/workflows/deploy.yml@main
    secrets:
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
      SF_JWT_KEY_B64: ${{ secrets.SF_JWT_KEY_B64 }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
