# In consumer repo
name: Trigger DevAssist Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: erinehart1/devAssist-Shared-Actions/.github/workflows/deploy.yml@main
    secrets:
      SF_JWT_KEY: ${{ secrets.HelloWorld123 }}
